server:
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

exception:
  trace: false

logging:
  level:
    com.ros.ewallet: info
    org.springframework: warn
    org.hibernate: error
    org.springframework.security: warn

app:
  security:
    cookieSecure: true
    cors:
      allowed-origins: ${cors_allowed_origins}
